#!/usr/bin/env bash
# Guard against accidental writes to sensitive or auto-generated files.
# Exit 2 = block the action and feed stderr back to Claude.

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')
[[ -z "$FILE_PATH" ]] && exit 0

# Block writes to environment files (secrets must be edited manually)
if [[ "$FILE_PATH" =~ (^|/)\.env($|\.) ]]; then
	echo "Blocked: Refusing to write to environment file '${FILE_PATH}'." >&2
	echo "Environment files contain secrets and must be edited manually." >&2
	exit 2
fi

# Block writes to Cloudflare local secrets file
if [[ "$FILE_PATH" =~ (^|/)\.dev\.vars($|\..*)$ ]]; then
	echo "Blocked: Refusing to write to '.dev.vars'." >&2
	echo ".dev.vars holds local Cloudflare secrets and must be edited manually." >&2
	echo "For prod secrets, run: wrangler secret put NAME" >&2
	exit 2
fi

# Block edits to D1 migration SQL (use bun db:generate instead)
if [[ "$FILE_PATH" =~ /drizzle/migrations/.*\.(sql|json)$ ]]; then
	echo "Blocked: Do not edit migration files directly: '${FILE_PATH}'." >&2
	echo "Run 'bun db:generate' to create new migrations from schema.ts." >&2
	exit 2
fi

# Block edits to TanStack Router auto-generated route tree
if [[ "$FILE_PATH" =~ routeTree\.gen\.ts$ ]]; then
	echo "Blocked: Do not edit routeTree.gen.ts — it is auto-generated by TanStack Router." >&2
	exit 2
fi

# Block edits to wrangler-generated binding types
if [[ "$FILE_PATH" =~ worker-configuration\.d\.ts$ ]]; then
	echo "Blocked: Do not edit worker-configuration.d.ts — it is auto-generated." >&2
	echo "Edit wrangler.jsonc and run 'bun cf-typegen' instead." >&2
	exit 2
fi

# Block edits to .wrangler local state
if [[ "$FILE_PATH" =~ /\.wrangler/ ]]; then
	echo "Blocked: '.wrangler/' is local state managed by wrangler. Do not edit." >&2
	exit 2
fi

exit 0
